#spring:
#  datasource:
#    username:root
#    password:
#    url:jdbc:mysql://localhost:3306/myusers
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    jpa:
#      show-sql: true
#      hibernate:
#        ddl-quto:update
#      properties.hibername.dialect:org.hibernate.dialect.MySQL5Dialect