package et.com.amanuwel.Entity;
// Generated Jun 11, 2021 4:59:37 PM by Hibernate Tools 5.2.0.Final


import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name="cart"
    ,catalog="myusers"
)
public class Cart  implements java.io.Serializable {


     private Long id;
     private Food food;
     private User user;
     private Integer quantity;
     private Boolean cart_status;
     @JsonIgnore
     private Set<OrderFood> orderFoods = new HashSet<OrderFood>(0);

    public Cart() {
    }

    public Cart(Food food, User user, Integer quantity, Boolean cart_status, Set<OrderFood> orderFoods) {
       this.food = food;
       this.user = user;
       this.quantity = quantity;
       this.cart_status = cart_status;
       this.orderFoods = orderFoods;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="food_id")
    public Food getFood() {
        return this.food;
    }
    
    public void setFood(Food food) {
        this.food = food;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id")
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="quantity")
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="cart_status")
    public Boolean getcart_status() {
        return this.cart_status;
    }
    
    public void setcart_status(Boolean cart_status) {
        this.cart_status = cart_status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cart")
    public Set<OrderFood> getOrderFoods() {
        return this.orderFoods;
    }
    
    public void setOrderFoods(Set<OrderFood> orderFoods) {
        this.orderFoods = orderFoods;
    }




}


