package et.com.amanuwel.Entity;
// Generated Jun 11, 2021 4:59:37 PM by Hibernate Tools 5.2.0.Final


import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Food generated by hbm2java
 */
@Entity
@Table(name="food"
    ,catalog="myusers"
)
public class Food  implements java.io.Serializable {


     private Long id;
     private String itemName;
     private Double price;
     private Boolean foodStatus;
     private String url;
     @JsonIgnore
     private Set<Cart> carts = new HashSet<Cart>(0);

    public Food() {
    }

    public Food(String itemName, Double price, Boolean foodStatus, String url, Set<Cart> carts) {
       this.itemName = itemName;
       this.price = price;
       this.foodStatus = foodStatus;
       this.url = url;
       this.carts = carts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="item_name", length=1024)
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    
    @Column(name="price", precision=22, scale=0)
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }

    
    @Column(name="food_status")
    public Boolean getFoodStatus() {
        return this.foodStatus;
    }
    
    public void setFoodStatus(Boolean foodStatus) {
        this.foodStatus = foodStatus;
    }

    
    @Column(name="url")
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="food")
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }




}


