package et.com.amanuwel.Entity;
// Generated Jun 11, 2021 4:59:37 PM by Hibernate Tools 5.2.0.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderFood generated by hbm2java
 */
@Entity
@Table(name="order_food"
    ,catalog="myusers"
)
public class OrderFood  implements java.io.Serializable {


     private Long id;
     private Cart cart;
     private User user;
     private Date booked_at;
     private String cancel_access_code;
     private Boolean statusid;
     private Integer total_cart;
     private Float total_price;

    public OrderFood() {
    }

    public OrderFood(Cart cart, User user, Date booked_at, String cancel_access_code, Boolean statusid, Integer total_cart, Float total_price) {
       this.cart = cart;
       this.user = user;
       this.booked_at = booked_at;
       this.cancel_access_code = cancel_access_code;
       this.statusid = statusid;
       this.total_cart = total_cart;
       this.total_price = total_price;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cart_id")
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customerid")
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="booked_at", length=19)
    public Date getbooked_at() {
        return this.booked_at;
    }
    
    public void setbooked_at(Date booked_at) {
        this.booked_at = booked_at;
    }

    
    @Column(name="cancel_access_code", length=1024)
    public String getcancel_access_code() {
        return this.cancel_access_code;
    }
    
    public void setcancel_access_code(String cancel_access_code) {
        this.cancel_access_code = cancel_access_code;
    }

    
    @Column(name="statusid")
    public Boolean getStatusid() {
        return this.statusid;
    }
    
    public void setStatusid(Boolean statusid) {
        this.statusid = statusid;
    }

    
    @Column(name="total_cart")
    public Integer gettotal_cart() {
        return this.total_cart;
    }
    
    public void settotal_cart(Integer total_cart) {
        this.total_cart = total_cart;
    }

    
    @Column(name="total_price", precision=12, scale=0)
    public Float gettotal_price() {
        return this.total_price;
    }
    
    public void settotal_price(Float total_price) {
        this.total_price = total_price;
    }




}


