package et.com.amanuwel.Entity;
// Generated Jun 11, 2021 4:59:37 PM by Hibernate Tools 5.2.0.Final


import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="myusers"
)
public class User  implements java.io.Serializable {


     private Long id;
     private String firstName;
     private String userEmail;
     private String userLocation;
     private String userName;
     private String userPass;
     private String userPhone;
     @JsonIgnore
     private Set<Cart> carts = new HashSet<Cart>(0);
     @JsonIgnore
     private Set<OrderFood> orderFoods = new HashSet<OrderFood>(0);

    public User() {
    }

    public User(String firstName, String userEmail, String userLocation, String userName, String userPass, String userPhone, Set<Cart> carts, Set<OrderFood> orderFoods) {
       this.firstName = firstName;
       this.userEmail = userEmail;
       this.userLocation = userLocation;
       this.userName = userName;
       this.userPass = userPass;
       this.userPhone = userPhone;
       this.carts = carts;
       this.orderFoods = orderFoods;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="first_name")
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="user_email")
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    
    @Column(name="user_location")
    public String getUserLocation() {
        return this.userLocation;
    }
    
    public void setUserLocation(String userLocation) {
        this.userLocation = userLocation;
    }

    
    @Column(name="user_name")
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="user_pass")
    public String getUserPass() {
        return this.userPass;
    }
    
    public void setUserPass(String userPass) {
        this.userPass = userPass;
    }

    
    @Column(name="user_phone")
    public String getUserPhone() {
        return this.userPhone;
    }
    
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<OrderFood> getOrderFoods() {
        return this.orderFoods;
    }
    
    public void setOrderFoods(Set<OrderFood> orderFoods) {
        this.orderFoods = orderFoods;
    }




}


